// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDueJVt_lFGyqiVhRBvMyngotoUOMGuIyU',
    appId: '1:600953862786:web:5bf260bc051e148958529b',
    messagingSenderId: '600953862786',
    projectId: 'quan-ly-chi-tieu-76343',
    authDomain: 'quan-ly-chi-tieu-76343.firebaseapp.com',
    storageBucket: 'quan-ly-chi-tieu-76343.firebasestorage.app',
    measurementId: 'G-6Z3RMTQD0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQdtLMRZMok5T2BcZZ6VxLrzLwqkpediI',
    appId: '1:600953862786:android:c4de1c324ce0726758529b',
    messagingSenderId: '600953862786',
    projectId: 'quan-ly-chi-tieu-76343',
    storageBucket: 'quan-ly-chi-tieu-76343.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyKqh-15JoG8Fl3P8T71b_RW6964a-BBc',
    appId: '1:600953862786:ios:9b52e6208f6869c258529b',
    messagingSenderId: '600953862786',
    projectId: 'quan-ly-chi-tieu-76343',
    storageBucket: 'quan-ly-chi-tieu-76343.firebasestorage.app',
    iosBundleId: 'com.example.quanLyChiTieu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyKqh-15JoG8Fl3P8T71b_RW6964a-BBc',
    appId: '1:600953862786:ios:9b52e6208f6869c258529b',
    messagingSenderId: '600953862786',
    projectId: 'quan-ly-chi-tieu-76343',
    storageBucket: 'quan-ly-chi-tieu-76343.firebasestorage.app',
    iosBundleId: 'com.example.quanLyChiTieu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDueJVt_lFGyqiVhRBvMyngotoUOMGuIyU',
    appId: '1:600953862786:web:7a759de43e079db658529b',
    messagingSenderId: '600953862786',
    projectId: 'quan-ly-chi-tieu-76343',
    authDomain: 'quan-ly-chi-tieu-76343.firebaseapp.com',
    storageBucket: 'quan-ly-chi-tieu-76343.firebasestorage.app',
    measurementId: 'G-4VJFD369S3',
  );
}
